import { defineVuetifyConfiguration } from "vuetify-nuxt-module/custom-configuration";

// マテリアルデザインのテーマを定義
const lightTheme = {
  dark: false,
  colors: {
    primary: "#006972",
    surfaceTint: "#006972",
    onPrimary: "#FFFFFF",
    primaryContainer: "#9DF0FB",
    onPrimaryContainer: "#004F56",
    secondary: "#4A6366",
    onSecondary: "#FFFFFF",
    secondaryContainer: "#CDE7EB",
    onSecondaryContainer: "#324B4E",
    tertiary: "#515E7D",
    onTertiary: "#FFFFFF",
    tertiaryContainer: "#D9E2FF",
    onTertiaryContainer: "#3A4664",
    error: "#BA1A1A",
    onError: "#FFFFFF",
    errorContainer: "#FFDAD6",
    onErrorContainer: "#93000A",
    background: "#F5FAFB",
    onBackground: "#171D1E",
    surface: "#F5FAFB",
    onSurface: "#171D1E",
    surfaceVariant: "#DBE4E6",
    onSurfaceVariant: "#3F484A",
    outline: "#6F797A",
    outlineVariant: "#BEC8CA",
    shadow: "#000000",
    scrim: "#000000",
    inverseSurface: "#2B3132",
    inverseOnSurface: "#ECF2F3",
    inversePrimary: "#81D3DF",
    primaryFixed: "#9DF0FB",
    onPrimaryFixed: "#001F23",
    primaryFixedDim: "#81D3DF",
    onPrimaryFixedVariant: "#004F56",
    secondaryFixed: "#CDE7EB",
    onSecondaryFixed: "#051F22",
    secondaryFixedDim: "#B1CBCF",
    onSecondaryFixedVariant: "#324B4E",
    tertiaryFixed: "#D9E2FF",
    onTertiaryFixed: "#0D1B36",
    tertiaryFixedDim: "#B9C6EA",
    onTertiaryFixedVariant: "#3A4664",
    surfaceDim: "#D5DBDC",
    surfaceBright: "#F5FAFB",
    surfaceContainerLowest: "#FFFFFF",
    surfaceContainerLow: "#EFF5F5",
    surfaceContainer: "#E9EFF0",
    surfaceContainerHigh: "#E3E9EA",
    surfaceContainerHighest: "#DEE4E4",
  },
};

const darkTheme = {
  dark: true,
  colors: {
    primary: "#81D3DF",
    surfaceTint: "#81D3DF",
    onPrimary: "#00363C",
    primaryContainer: "#004F56",
    onPrimaryContainer: "#9DF0FB",
    secondary: "#B1CBCF",
    onSecondary: "#1C3437",
    secondaryContainer: "#324B4E",
    onSecondaryContainer: "#CDE7EB",
    tertiary: "#B9C6EA",
    onTertiary: "#23304D",
    tertiaryContainer: "#3A4664",
    onTertiaryContainer: "#D9E2FF",
    error: "#FFB4AB",
    onError: "#690005",
    errorContainer: "#93000A",
    onErrorContainer: "#FFDAD6",
    background: "#0E1415",
    onBackground: "#DEE4E4",
    surface: "#0E1415",
    onSurface: "#DEE4E4",
    surfaceVariant: "#3F484A",
    onSurfaceVariant: "#BEC8CA",
    outline: "#899294",
    outlineVariant: "#3F484A",
    shadow: "#000000",
    scrim: "#000000",
    inverseSurface: "#DEE4E4",
    inverseOnSurface: "#2B3132",
    inversePrimary: "#006972",
    primaryFixed: "#9DF0FB",
    onPrimaryFixed: "#001F23",
    primaryFixedDim: "#81D3DF",
    onPrimaryFixedVariant: "#004F56",
    secondaryFixed: "#CDE7EB",
    onSecondaryFixed: "#051F22",
    secondaryFixedDim: "#B1CBCF",
    onSecondaryFixedVariant: "#324B4E",
    tertiaryFixed: "#D9E2FF",
    onTertiaryFixed: "#0D1B36",
    tertiaryFixedDim: "#B9C6EA",
    onTertiaryFixedVariant: "#3A4664",
    surfaceDim: "#0E1415",
    surfaceBright: "#343A3B",
    surfaceContainerLowest: "#090F10",
    surfaceContainerLow: "#171D1E",
    surfaceContainer: "#1B2122",
    surfaceContainerHigh: "#252B2C",
    surfaceContainerHighest: "#303637",
  },
};

export default defineVuetifyConfiguration({
  defaults: {
    VCard: {
      elevation: 1,
      class: "pa-4",
      maxWidth: 600,
      color: "surfaceContainer",
      rounded: "lg",
    },
    VBtn: {
      color: "primary",
      variant: "flat",
    },
    // 他のコンポーネントもここに追記可！
  },
  // your Vuetify options here
  theme: {
    defaultTheme: "light",
    themes: {
      light: lightTheme,
      dark: darkTheme,
    },
  },
});
